#!/bin/sh /etc/rc.common
# Copyright (C) 2021 OpenWrt.org
# Copyright (c) 2021 billsq <billsq@billsq.me>

START=89
STOP=11

USE_PROCD=1
PROG=/usr/bin/tinymapper

validate_tinymapper_section()
{
	uci_validate_section tinymapper tinymapper "${1}" \
		'enabled:bool:0'		\
		'local:string'			\
		'remote:string'			\
		'tcp:bool:1' 			\
		'udp:bool:0' 			\
		'sock_buf:integer:1024' \
		'log_level:integer:4'
}

start_instance()
{
	local section="$1"

	local enabled local remote tcp udp sock_buf log_level

	validate_tinymapper_section $section || {
		echo "validation failed"
		return 1
	}

	if [ "${enabled}" -ne 1 ]; then
		return 1
	fi

	if [ "${tcp}" -ne 1 ] && [ "${udp}" -ne 1 ]; then
		return 1
	fi

	procd_open_instance
	procd_set_param respawn
	procd_set_param stderr 1
	procd_set_param stdout 1

	procd_set_param command "${PROG}"

	host=$(echo $remote | cut -d : -f 1)
	port=$(echo $remote | cut -d : -f 2)
	if [[ ! $host =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
		resolved=$(dig +short $host | tail -n1)
		if [[ ! $resolved =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
			logger -t "tinyPortMapper" "failed to resolve remote ${host}, got ${resolved}"
			return 1
		fi
		logger -t "tinyPortMapper" "resolved remote ${host} to ${resolved}"
		host=$resolved
	fi
	procd_append_param command -r "${host}:${port}"
	
	host=$(echo $local | cut -d : -f 1)
	port=$(echo $local | cut -d : -f 2)
	if [[ ! $host =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
		resolved=$(dig +short $host | tail -n1)
		if [[ ! $resolved =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
			logger -t "tinyPortMapper" "failed to resolve local ${host}, got ${resolved}"
			return 1
		fi
		logger -t "tinyPortMapper" "resolved local ${host} to ${resolved}"
		host=$resolved
	fi
	procd_append_param command -l "${host}:${port}"
	
	if [ "${tcp}" -eq 1 ]; then
		procd_append_param command -t
	fi

	if [ "${udp}" -eq 1 ]; then
		procd_append_param command -u
	fi
	
	procd_append_param command --sock-buf "${sock_buf}"
	procd_append_param command --log-level "${log_level}"
	procd_append_param command --disable-color
	
	procd_set_param respawn ${respawn_threshold:-60} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_close_instance
}

start_service()
{
	config_load 'tinymapper'
	config_foreach start_instance 'tinymapper'
}

stop_service()
{
	service_stop ${PROG}
}

service_triggers()
{
	procd_add_reload_trigger "tinymapper"
	procd_add_validation validate_tinymapper_section
}
